import org.gradle.nativeplatform.internal.DefaultTargetMachineFactory

rootProject.name = 'buildabrowser'
include(
    ':Common', ':Infra',
    ':CSSBase', ':CSSEngine', ':Renderer',
    ':PainterCore', ':PainterSkija', ':PainterJava2D',
    ':DebuggerCore', ':DebuggerSwing',
    ':DOM', ':HTML', ':HTMLParser',':Browser', ':Network',
    ':A11YCore', ':A11YAccessKit',
    ':Stream', ':Fetch', ':Cookies', ':CookiesSQLite',
    ':Embedding:StandardCommon', ':Embedding:Swing')

def localAk4j = file('../AK4J')

/*if (localAk4j.exists()) {
    includeBuild(localAk4j) {
        dependencySubstitution {
            substitute module('com.github.BuildABrowser:AK4J') using project(':lib')
            substitute module('com.github.BuildABrowser.AccessKit4J:AccessKit4J-natives-linux') using project(':lib')
        }
    }
}*/