plugins {
    id 'java-library'
}

dependencies {
    api project(':Renderer')

    implementation "io.github.humbleui:${skijaNatives}:${skijaVersion}"

	implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-harfbuzz"
	implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-jawt"
	implementation "org.lwjgl:lwjgl::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-harfbuzz::$lwjglNatives"
	implementation "org.lwjgl:lwjgl-opengl::$lwjglNatives"
	implementation("org.lwjglx:lwjgl3-awt:${lwjgl3_awtVersion}") {
        exclude group: 'org.lwjgl'
    }
}