plugins {
    id 'java-library'
}

dependencies {
    api project(':Renderer')

    api "io.github.humbleui:skija-shared:${skijaVersion}"

    api platform("org.lwjgl:lwjgl-bom:${lwjglVersion}")
    api "org.lwjgl:lwjgl"
    api "org.lwjgl:lwjgl-harfbuzz"
    api "org.lwjgl:lwjgl-opengl"
    api "org.lwjgl:lwjgl-jawt"

    implementation("org.lwjglx:lwjgl3-awt:${lwjgl3_awtVersion}") {
        exclude group: 'org.lwjgl'
    }
}